### ISSUE TITLE
[BUG] data timestamp consistency violated with eCAL.

### ISSUE THREAD

**Issue by ZhenshengLee** [ZhenshengLee/performance_test#1]
### steps

```sh
mkdir experiment
# t1
./install/performance_test/lib/performance_test/perf_test -c ECAL --msg Array1k -p 0 -s 1
# t2
./install/performance_test/lib/performance_test/perf_test -c ECAL --msg Array1k -p 1 -s 0
```

### actual

```sh
terminate called after throwing an instance of 'std::runtime_error'             
  what():  Data consistency violated. Received sample with not strictly older timestamp. Time diff: -5739 Data Time: 435507319158649                                                                   
Aborted (core dumped)
```

### comment

qos function of eCAL is abnormal.

EDIT: 

### aditional info
Simply comment the qos settings for CSubscriber and CPublisher will ~~clear~~ NOT CLEAR this fault.

```sh
// m_publisher->SetQOS(writerQos);
// m_subscriber->SetQOS(ReaderQos);
m_publisher->ShmSetBufferCount(1);
```

will clear this fault

But this issue needs to be fixed.

**Comment by rex-schilasky** [comment]
Should be fixed in the latest versions too.

**Comment by ZhenshengLee** [comment]
> Should be fixed in the latest versions too.

@rex-schilasky  it still appears in the latest version #4

**Comment by rex-schilasky** [comment]
Okay, I will check this today more carefully.

**Comment by ZhenshengLee** [comment]
> Okay, I will check this today more carefully.

this problem disapear in automatic tests, but apear in handy test using scripts.

I would like to close this now.
