### ISSUE TITLE
[communication] unbounded message size doesn't work

### ISSUE THREAD

**Issue by wlfrdwu** [ZhenshengLee/performance_test#13]
reproduce process:
1. test cmd > perf_test -c FastRTPS -m UnboundedSequence --unbounded-msg-size 1024000 -p 1 -s 0
2. check message size in the msg serialization. performance_test::msg::FastDDSGen::UnboundedSequence::serialize @ fast_rtps/gen/fast_rtps/UnboundedSequence.cxx
3. The m_unbounded_sequence.size() is always zero.

请确认上述问题（在fastrtps通信方式下，unbounded-msg-size参数没有设置到unbound message消息体中）是否已在1.3.7版本之后的版本中修复，谢谢

**Comment by ZhenshengLee** [comment]
@wlfrdwu  Thanks for your report!

此问题不属于本库的新增功能。
请到Apex.AI 官方仓库提交issue ，https://gitlab.com/ApexAI/performance_test

**Comment by wlfrdwu** [comment]
> @wlfrdwu Thanks for your report!
> 
> 此问题不属于本库的新增功能。 请到Apex.AI 官方仓库提交issue ，https://gitlab.com/ApexAI/performance_test

谢谢，问题关闭

**Comment by ZhenshengLee** [comment]
close this.
