### ISSUE TITLE
 docker build . -f dockerfiles/Dockerfile.FastDDS -t performance_test_fast_dds  failed?

### ISSUE THREAD

**Issue by Eternity1987** [ZhenshengLee/performance_test#14]
![image](https://github.com/user-attachments/assets/7bf781b7-e4cd-4336-b1b5-d45edb51f20e)

**Comment by ZhenshengLee** [comment]
The docker support is not available in this repo.

And, as the readme said, please goto the official site to get the best and latest code.

https://github.com/ZhenshengLee/performance_test/blob/7ce2c8efda4f927af78684e054c840cbf51819d5/README.md?plain=1#L3
