### ISSUE TITLE
Why not just make an MR to performance_test to add eCAL and fast DDS there?

### ISSUE THREAD

**Issue by flynneva** [ZhenshengLee/performance_test#9]
@ZhenshengLee awesome work! Would be great if you could make an MR / PR back to `performance_test` so that others can also test `eCAL` and `fastdds` like you did here.

Would this be something you or @rex-schilasky would consider?

Also, it appears you had some issues setting up `cyclonedds` zero copy (specifically configuring the roudi). Would be happy to help you out here if needed.

**Comment by ZhenshengLee** [comment]
Hi @flynneva 

> Would be great if you could make an MR / PR back to performance_test so that others can also test eCAL and fastdds like you did here.

I'd like to make a MR to the official repo, after the job of developing an image zero-copy example in https://github.com/ZhenshengLee/ros2_shm_msgs, so the MR/PR may be created in about two weeks.

> Also, it appears you had some issues setting up cyclonedds zero copy (specifically configuring the roudi). Would be happy to help you out here if needed.

Yes, but I followed the config in https://github.com/ZhenshengLee/performance_test/blob/outdoor/master/dockerfiles/roudi_config.toml , that can be tracked in another issue.

Thanks.

**Comment by ZhenshengLee** [comment]
@flynneva 

Track with https://gitlab.com/ApexAI/performance_test/-/merge_requests/322

Closing this.
